on:
  push:
    branches:
      - deploy-on-nginx
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  check-build:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: List files in build
      run: |
            ls -al build

  copy-configs:
    name: "copy configs"
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - uses: actions/checkout@master
      - 
        name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
          port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
          username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
          password: ${{ secrets.RECETTE_APPLICATIONS_PASSWPRD }}
          key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
          source: "app-zeeven.conf"
          target: "/opt/applications/zeeven/app-zeeven"
  
  restart-nginx:
    name: "Restart nginx"
    runs-on: ubuntu-latest
    needs: [check-build]
    steps:
    - name: Restart nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
        port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
        username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
        password: ${{ secrets.RECETTE_APPLICATIONS_PASSWPRD }}
        key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
        script: |
          sudo service nginx restart